model:
  base_learning_rate: 4.5e-7
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 192
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [12]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 250001
        disc_weight: 0.2
        codebook_weight: 1.0

data:
  target: tools.gr_datamodule.GRDataModule
  params:
    batch_size: 30
    num_workers: 24
    train:
      target: taming.data.gr.GRTrain
      params:
        root_dir: /mnt/bn/robotics-lq2024/wht/vq-data/
        filelist_txt: /mnt/bn/robotics-lq2024/wht/vq-data/gr_data_real/train_vqgan.txt
        size: 192
    validation:
      target: taming.data.gr.GRVal
      params:
        root_dir: /mnt/bn/robotics-lq2024/wht/vq-data/
        filelist_txt: /mnt/bn/robotics-lq2024/wht/vq-data/gr_data_real/val_vqgan.txt
        size: 192
